/**
 * Reads data/generated-credits.json — the output of the licence gate (§12.3, §12.5).
 *
 * Server-only. The file is generated by `scripts/verify-licenses.ts` on `predev`/`prebuild`
 * and is gitignored, so this must degrade rather than throw: a developer who has not yet run
 * the gate should see an empty credits modal, not a 500.
 */

import 'server-only';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

export type CreditEntry = {
  assetId: string;
  file: string;
  author: string;
  license: string;
  sourceUrl: string;
  sourceSite: string;
  attributionText: string | null;
  modifications: string;
};

export type OriginalEntry = { assetId: string; file: string; modifications: string };

export type Credits = {
  generatedOn: string;
  entries: CreditEntry[];
  originals: OriginalEntry[];
};

const EMPTY: Credits = { generatedOn: '', entries: [], originals: [] };

export function getCredits(): Credits {
  try {
    const raw = readFileSync(join(process.cwd(), 'data', 'generated-credits.json'), 'utf8');
    const parsed = JSON.parse(raw) as Partial<Credits>;
    return {
      generatedOn: parsed.generatedOn ?? '',
      entries: parsed.entries ?? [],
      originals: parsed.originals ?? [],
    };
  } catch {
    // Gate not run yet. `pnpm verify:licenses` fixes it; an empty modal is the right fallback.
    return EMPTY;
  }
}
