/**
 * GENERATED by scripts/model/prepare-stage.mjs — do not edit by hand.
 * The circular stage platform (turntable + slatted backdrop + light rig) that floors
 * every 3D bay. Re-run the script on a new source to re-point the site.
 */
export const STAGE_PLATFORM_URL = '/models/stage-platform.fe76e38e.glb';
