/**
 * prepare-stage — process Hisan's circular stage platform for use as the bay floor.
 *
 * Source: Tripo-generated, one fused mesh (133,791 tris) with one baked 4096² JPEG atlas
 * (black + tan — already on-palette). The square light-rig frame and the slatted backdrop
 * are fused to the turntable, so nothing is removed: tinted dark it reads as a showroom
 * display stand, which is what it is.
 *
 *   node scripts/model/prepare-stage.mjs "circular stage platform 3d model.glb"
 *
 * Output: public/models/stage-platform.<hash>.glb (meshopt, webp atlas) plus
 * src/lib/stage-platform.ts carrying the resolved URL for the scene to import.
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { meshopt, simplify, prune, dedup, textureCompress, weld } from '@gltf-transform/functions';
import sharp from 'sharp';
import { MeshoptEncoder, MeshoptDecoder, MeshoptSimplifier } from 'meshoptimizer';

const [input] = process.argv.slice(2);
if (!input) {
  console.error('usage: prepare-stage.mjs <source.glb>');
  process.exit(1);
}
await MeshoptEncoder.ready;
await MeshoptDecoder.ready;
await MeshoptSimplifier.ready;

const io = new NodeIO()
  .registerExtensions(ALL_EXTENSIONS)
  .registerDependencies({ 'meshopt.encoder': MeshoptEncoder, 'meshopt.decoder': MeshoptDecoder });

const countTris = (doc) => {
  let n = 0;
  for (const m of doc.getRoot().listMeshes())
    for (const p of m.listPrimitives()) n += p.getIndices().getCount() / 3;
  return Math.round(n);
};

const doc = await io.read(input);
const sourceTris = countTris(doc);

await doc.transform(
  weld(),
  dedup(),
  prune(),
  textureCompress({ encoder: sharp, targetFormat: 'webp', quality: 90 }),
);

// KHR_materials_volume on an opaque platform is inert weight; drop it so the runtime
// material stays a plain MeshStandardMaterial.
for (const mat of doc.getRoot().listMaterials()) {
  mat.setExtension('KHR_materials_volume', null);
}

await doc.transform(meshopt({ encoder: MeshoptEncoder, level: 'high' }));

const outDir = path.join('public', 'models');
fs.mkdirSync(outDir, { recursive: true });
const tmp = path.join(outDir, '.tmp-stage-platform.glb');
await io.write(tmp, doc);

const buf = fs.readFileSync(tmp);
const hash = crypto.createHash('sha256').update(buf).digest('hex').slice(0, 8);
const finalName = `stage-platform.${hash}.glb`;
for (const f of fs.readdirSync(outDir))
  if (f.startsWith('stage-platform.') && f !== finalName) fs.unlinkSync(path.join(outDir, f));
fs.renameSync(tmp, path.join(outDir, finalName));

const tris = countTris(doc);
console.log(`stage-platform  ${tris} tris  ${(buf.length / 1048576).toFixed(2)} MB  public/models/${finalName}`);

// The scene imports the URL from here, so a re-run of this script re-points the site by
// regenerating one file — no component edits.
const ts = `/**
 * GENERATED by scripts/model/prepare-stage.mjs — do not edit by hand.
 * The circular stage platform (turntable + slatted backdrop + light rig) that floors
 * every 3D bay. Re-run the script on a new source to re-point the site.
 */
export const STAGE_PLATFORM_URL = '/models/${finalName}';
`;
fs.writeFileSync('src/lib/stage-platform.ts', ts);
console.log('wrote src/lib/stage-platform.ts');
